using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace ChBrowser.Services.Donguri;

/// <summary>
/// Netscape 形式 cookies.txt をストアにした最小限の Cookie 管理。
/// 5ch.io の MonaTicket / acorn 程度しか扱わないので RFC 6265 完全準拠は狙わない。
/// MonazillaClient は <c>UseCookies=false</c> で動かしているため、各リクエストごとに
/// <see cref="ApplyToRequest"/> / <see cref="MergeFromResponse"/> を呼ぶ責務はサービス層側にある。
///
/// 永続化は <see cref="SaveAsync"/> を明示的に呼んだ時だけ。Set-Cookie マージのたびに
/// ディスクに書きには行かない (失効間際の書き込みでも 1 度のセッションで十分なため)。
/// </summary>
public sealed class CookieJar
{
    private const string Header = "# Netscape HTTP Cookie File\n# This file is generated by ChBrowser.\n";

    private readonly string                      _path;
    private readonly object                      _lock = new();
    private readonly Dictionary<CookieKey, Entry> _store = new();

    public CookieJar(string path)
    {
        _path = path;
        TryLoad();
    }

    /// <summary>(domain,path,name) でユニーク。Netscape 形式の path は通常 "/"。</summary>
    private readonly record struct CookieKey(string Domain, string Path, string Name);

    private sealed record Entry(
        string         Domain,
        bool           IncludeSubdomains,
        string         Path,
        bool           Secure,
        DateTimeOffset Expires,    // session cookie は MaxValue
        string         Name,
        string         Value);

    /// <summary>指定 URL 向けに Cookie ヘッダ用の "name=value; name=value" 文字列を組み立てる。
    /// 期限切れは除外。<paramref name="namePredicate"/> が指定されていれば、それで真になる name の Cookie だけ採用する
    /// (= 認証モードによる Cookie 取捨選択用)。</summary>
    public string BuildCookieHeader(Uri uri, Func<string, bool>? namePredicate = null)
    {
        var now   = DateTimeOffset.UtcNow;
        var parts = new List<string>();
        lock (_lock)
        {
            foreach (var e in _store.Values)
            {
                if (e.Expires < now)                                   continue;
                if (e.Secure && uri.Scheme != Uri.UriSchemeHttps)      continue;
                if (!HostMatches(uri.Host, e.Domain, e.IncludeSubdomains)) continue;
                if (!uri.AbsolutePath.StartsWith(e.Path, StringComparison.Ordinal)) continue;
                if (namePredicate is not null && !namePredicate(e.Name)) continue;
                parts.Add($"{e.Name}={e.Value}");
            }
        }
        return string.Join("; ", parts);
    }

    /// <summary>ストア内の全 Cookie を削除する。設定 → 通信 → 「Cookie をすべて削除」から呼ばれる。
    /// 永続化 (cookies.txt 書き換え) はこのメソッドではしない — 呼び出し側で <see cref="SaveAsync"/> を呼ぶ。</summary>
    public void Clear()
    {
        lock (_lock) _store.Clear();
    }

    /// <summary><see cref="BuildCookieHeader"/> の結果を request の Cookie ヘッダにセット。
    /// 何も無ければ何もしない。</summary>
    public void ApplyToRequest(HttpRequestMessage req)
    {
        if (req.RequestUri is null) return;
        var header = BuildCookieHeader(req.RequestUri);
        if (header.Length == 0) return;
        req.Headers.Remove("Cookie");
        req.Headers.TryAddWithoutValidation("Cookie", header);
    }

    /// <summary>レスポンスの Set-Cookie をすべて取り込み、店内ストアを更新する。</summary>
    public void MergeFromResponse(HttpResponseMessage resp)
    {
        if (!resp.Headers.TryGetValues("Set-Cookie", out var values)) return;
        var requestHost = resp.RequestMessage?.RequestUri?.Host ?? "";
        foreach (var raw in values)
        {
            var entry = ParseSetCookie(raw, requestHost);
            if (entry is null) continue;
            var key = new CookieKey(entry.Domain, entry.Path, entry.Name);
            lock (_lock)
            {
                if (entry.Expires <= DateTimeOffset.UtcNow) _store.Remove(key);
                else                                       _store[key] = entry;
            }
        }
    }

    /// <summary>指定ドメイン (サブドメイン一致を含む) と name に一致する Cookie を取り出す。
    /// 該当無しなら null。<see cref="DonguriService"/> から acorn/MonaTicket の取り出しに使う。</summary>
    public string? Find(string host, string name)
    {
        var now = DateTimeOffset.UtcNow;
        lock (_lock)
        {
            foreach (var e in _store.Values)
            {
                if (e.Name != name)                                    continue;
                if (e.Expires < now)                                   continue;
                if (!HostMatches(host, e.Domain, e.IncludeSubdomains)) continue;
                return e.Value;
            }
        }
        return null;
    }

    /// <summary>指定ドメイン (サブドメイン一致含む) の name に一致する Cookie をストアから削除。
    /// broken_acorn からの復旧などで使う。</summary>
    public void Remove(string host, string name)
    {
        lock (_lock)
        {
            var keys = _store.Keys
                .Where(k => k.Name == name &&
                            HostMatches(host, k.Domain, _store[k].IncludeSubdomains))
                .ToList();
            foreach (var k in keys) _store.Remove(k);
        }
    }

    /// <summary>現在のストア内容を Netscape 形式テキストとしてディスクに書き出す。
    /// 期限切れエントリは除外。</summary>
    public async Task SaveAsync(CancellationToken ct = default)
    {
        var sb  = new StringBuilder(Header);
        var now = DateTimeOffset.UtcNow;
        List<Entry> snapshot;
        lock (_lock)
        {
            snapshot = _store.Values.Where(e => e.Expires > now).ToList();
        }
        foreach (var e in snapshot)
        {
            // domain  includeSubdomains  path  secure  expiration_unix  name  value
            sb.Append(e.IncludeSubdomains ? "." + TrimLeadingDot(e.Domain) : e.Domain).Append('\t');
            sb.Append(e.IncludeSubdomains ? "TRUE" : "FALSE").Append('\t');
            sb.Append(e.Path).Append('\t');
            sb.Append(e.Secure ? "TRUE" : "FALSE").Append('\t');
            sb.Append(e.Expires == DateTimeOffset.MaxValue ? "0" : e.Expires.ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture)).Append('\t');
            sb.Append(e.Name).Append('\t');
            sb.Append(e.Value).Append('\n');
        }
        Directory.CreateDirectory(Path.GetDirectoryName(_path)!);
        var tmp = _path + ".tmp";
        await File.WriteAllTextAsync(tmp, sb.ToString(), Encoding.UTF8, ct).ConfigureAwait(false);
        File.Move(tmp, _path, overwrite: true);
    }

    private void TryLoad()
    {
        if (!File.Exists(_path)) return;
        try
        {
            foreach (var raw in File.ReadAllLines(_path, Encoding.UTF8))
            {
                if (string.IsNullOrWhiteSpace(raw)) continue;
                if (raw.StartsWith('#'))            continue;
                var f = raw.Split('\t');
                if (f.Length < 7) continue;
                var domainRaw       = f[0];
                var includeSub      = string.Equals(f[1], "TRUE", StringComparison.OrdinalIgnoreCase) || domainRaw.StartsWith('.');
                var path            = f[2];
                var secure          = string.Equals(f[3], "TRUE", StringComparison.OrdinalIgnoreCase);
                var expiresUnixStr  = f[4];
                var name            = f[5];
                var value           = f[6];
                var domain          = TrimLeadingDot(domainRaw);
                var expires         = expiresUnixStr == "0"
                    ? DateTimeOffset.MaxValue
                    : long.TryParse(expiresUnixStr, NumberStyles.Integer, CultureInfo.InvariantCulture, out var unix)
                        ? DateTimeOffset.FromUnixTimeSeconds(unix)
                        : DateTimeOffset.MinValue;
                if (expires < DateTimeOffset.UtcNow) continue;
                var entry = new Entry(domain, includeSub, path, secure, expires, name, value);
                _store[new CookieKey(domain, path, name)] = entry;
            }
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[CookieJar] load failed: {ex.Message}");
        }
    }

    /// <summary>Set-Cookie 1 行をパース。属性は ';' 区切り、名前=値 / Domain= / Path= / Expires= / Max-Age= / Secure。
    /// パース失敗・要件不足は null を返す。</summary>
    private static Entry? ParseSetCookie(string raw, string defaultHost)
    {
        var segments = raw.Split(';');
        if (segments.Length == 0) return null;
        var firstEq = segments[0].IndexOf('=');
        if (firstEq <= 0) return null;
        var name  = segments[0][..firstEq].Trim();
        var value = segments[0][(firstEq + 1)..].Trim();
        if (string.IsNullOrEmpty(name)) return null;

        var domain            = defaultHost;
        var includeSubdomains = false;
        var path              = "/";
        var secure            = false;
        var expires           = DateTimeOffset.MaxValue;

        for (var i = 1; i < segments.Length; i++)
        {
            var seg = segments[i].Trim();
            if (seg.Length == 0) continue;
            var eq = seg.IndexOf('=');
            var k  = (eq < 0 ? seg : seg[..eq]).Trim().ToLowerInvariant();
            var v  = eq < 0 ? "" : seg[(eq + 1)..].Trim();
            switch (k)
            {
                case "domain":
                    if (!string.IsNullOrEmpty(v))
                    {
                        includeSubdomains = v.StartsWith('.');
                        domain            = TrimLeadingDot(v);
                    }
                    break;
                case "path":   if (!string.IsNullOrEmpty(v)) path = v; break;
                case "secure": secure = true; break;
                case "expires":
                    if (DateTimeOffset.TryParse(v, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out var ex))
                        expires = ex;
                    break;
                case "max-age":
                    if (long.TryParse(v, NumberStyles.Integer, CultureInfo.InvariantCulture, out var sec))
                        expires = sec <= 0 ? DateTimeOffset.MinValue : DateTimeOffset.UtcNow.AddSeconds(sec);
                    break;
            }
        }
        if (string.IsNullOrEmpty(domain)) return null;
        return new Entry(domain, includeSubdomains, path, secure, expires, name, value);
    }

    private static bool HostMatches(string requestHost, string cookieDomain, bool includeSubdomains)
    {
        if (string.Equals(requestHost, cookieDomain, StringComparison.OrdinalIgnoreCase)) return true;
        return includeSubdomains
            && requestHost.EndsWith("." + cookieDomain, StringComparison.OrdinalIgnoreCase);
    }

    private static string TrimLeadingDot(string s) => s.StartsWith('.') ? s[1..] : s;
}
